title: Brandon Fallin
description: PhD Candidate @ University of Florida
domain: brandoncfallin.com   
url: https://brandoncfallin.com
baseurl: ""

plugins:
  - jekyll-image-size

# Build settings
markdown: kramdown
kramdown:
mathjax: true

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Sass settings
sass:
  style: compressed

# Collections
collections:
  publications:
    output: false
  work_experiences:
    output: false
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Make sure microblog posts are included in the site's posts
defaults:
  - scope:
      path: ""
      type: "microblog"
    values:
      layout: "microblog_post"
