name: sync-bluesky

on:
  workflow_dispatch: # allow manual runs
  schedule:
    - cron: "0 7 * * *" # run daily at 7 AM UTC

permissions:
  contents: write # Needed to commit back to the repository

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Use a more recent version of checkout

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install atproto requests Pillow

      - name: Run sync script
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        # The path should be relative to the repository root
        run: python .github/scripts/sync_bluesky.py

      - name: Commit and push new posts and timestamp
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"

          # Add all new posts, images, AND the timestamp file
          git add _posts/ assets/images/microblog/ .last_run_timestamp

          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No new posts or timestamp to commit."
          else
            # Commit with a message that includes [skip ci] to prevent re-triggering the workflow
            git commit -m "Auto-sync Bluesky posts and update timestamp [skip ci]"
            git push
          fi
