name: Sync Bluesky Posts

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: "0 7 * * *" # every day at 7 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install atproto requests

      - name: Run sync script
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: python .github/scripts/sync_bluesky.py

      - name: Commit and push new posts
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add _posts/ assets/images/microblog/
          git commit -m "Auto-sync Bluesky posts" || echo "No changes"
          git push
